### ISSUE TITLE
Support Callgrind client requests

### ISSUE THREAD

**Issue by osiewicz** [osiewicz/calliper#4]
It would be cool to be able to stop and start instrumentation of some parts of code, e.g. a costly setup. Such code could reside in `utils` or a separate crate altogether.

**Comment by osiewicz** [comment]
The code is now in main branch. I utilized @2dav's [crabgrind crate](https://github.com/2dav/crabgrind#crabgrind).

**Comment by osiewicz** [comment]
It seems that crabgrind is licensed under GPL2. :x

**Comment by osiewicz** [comment]
Based on precedent in https://github.com/tauri-apps/tauri/discussions/5561 it seems like a dependency on GPL2 crabgrind does not make calliper itself a GPL2 codebase and the burden of GPL is on calliper users. It only really matters if they decide to distribute their benchmarks as binaries, which seems dubious at best.

**Comment by 2dav** [comment]
Hey! Glad that `crabgrind` found application in the development of `iai` ideas! 

As of choosing GPL2 license, i haven't put thought in it initially and just followed Valgrind license to be safe, it seems the restrictions can be eased 

https://valgrind.org/docs/manual/manual-intro.html
>  The valgrind/*.h headers that you may wish to include in your code (eg. valgrind.h, memcheck.h, helgrind.h, etc.) are distributed under a BSD-style license, so you may include them in your code without worrying about license conflicts

this is exactly the case, so licensing as MIT now, no concerns for `calliper` users.
